### ISSUE TITLE
Crashes?

### ISSUE THREAD

**Issue by Faulkal** [Rawns/Reddit-Wallpaper-Changer#72]
Hi, 

Im trying to use the current version but when i launch the app, it must crash right away because nothing is in the system tray and nothing is running on task manager. v1.0.6 worked though. Im running windows 10.

**Comment by Rawns** [comment]
This is caused by a corrupt settings file. To fix this:
Navigate to C:\Users<your profile>\AppData\Local_uRawns\ and delete all the folders within. They should all start Reddit_Wallpaper_Changer._Uri<uid>.
These are the RWC setting files/folders. Once deleted, launch RWC and it will rebuild the new settings files.
